/**
 * @file
 * @addtogroup pctrl_logging_utils
 *
 * A logging subsystem that allows run time control for the logging level.
 * Log messages are passed back to the application for output.
 * Log messages are given sequence numbers.
 * A time callback can be provided by the application for the timestamp for each output line.
 * Log messages are mutex protected across threads so that log messages do not interrupt each other.
 */
/*
 * In the main application file:
 *
 *  Log output callback function - The application decides what and how logging is to be output
 *
 *  int app_log_output_callback(CY_PCTRL_LOG_FACILITY_T facility, CY_PCTRL_LOG_LEVEL_T level, char
 * *logmsg)
 *  {
 *      (void)facility;     // Can be used to decide to reduce the output or send output to remote
 * logging
 *      (void)level;        // Can be used to decide to reduce the output, although the output has
 * already been
 *                          // limited by the log routines
 *
 *      return printf( "%s\n", logmsg);   // print directly to console
 *  }
 *
 *
 *  Log time callback - get the current time for the log message timestamp in ms
 *
 *  cy_rslt_t app_log_time(uint32_t* time)
 *  {
 *      if (time != NULL)
 *      {
 *          *time = get_time_ms(); // get system time (in ms)
 *      }
 *      return CY_RSLT_SUCCESS;
 *  }
 *
 *
 *  Log initialization - default or OFF, no output from any facility
 *
 *  result = cy_pctrl_log_init(CY_PCTRL_LOG_OFF, app_log_output_callback, app_log_time);
 *  if (result != CY_RSLT_SUCCESS)
 *  {
 *      printf("cy_pctrl_log_init() FAILED %ld\n", result);
 *  }
 *
 *
 *  Example using the TEST facility
 *
 *  // Sets the log message level to WARNING
 *  cy_pctrl_log_set_facility_level(CYLF_PCTRL_TEST, CY_PCTRL_LOG_WARNING);
 *
 *  // Bypasses the facility/level check and always print message
 *  // Calls app_log_output_callback(CYLF_PCTRL_DEF, CY_PCTRL_LOG_PRINT, logmsg)
 *  cy_pctrl_log_printf("MIDDLEWARE message: always print.");
 *
 *  // Print if PCTRL_CYLF_TEST level is CY_PCTRL_LOG_WARNING or higher
 *  cy_pctrl_log_msg(CYLF_PCTRL_MIDDLEWARE, CY_PCTRL_LOG_ERROR, "MIDDLEWARE message: ERROR");
 *  // Print if PCTRL_CYLF_TEST level is CY_PCTRL_LOG_WARNING or higher
 *  cy_pctrl_log_msg(CYLF_PCTRL_MIDDLEWARE, CY_PCTRL_LOG_WARNING, "MIDDLEWARE message: WARNING");
 *
 *  Output:
 *
 *  MIDDLEWARE message: always print.
 *  MIDDLEWARE message: ERROR
 *  MIDDLEWARE message: WARNING
 */

#ifndef CY_PCTRL_LOG_H__
#define CY_PCTRL_LOG_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdarg.h>
#include "cy_result.h"

#ifdef PCTRL_ENABLE_LOGS
#define cy_pctrl_log_msg cy_pctrl_log_msg_
#define cy_pctrl_assert_msg cy_pctrl_assert_msg_
#else
#define cy_pctrl_log_msg(facility, level, fmt, ...)
#define cy_pctrl_assert_msg(assertion, facility, level, fmt, ...)
#endif

#define cy_pctrl_assert_msg_(assertion, facility, level, fmt, ...)    \
    do { if (!(assertion) ) { cy_pctrl_log_msg_(facility, level, fmt, __VA_ARGS__); CY_ASSERT_HANDLER(); } } while (0)

/******************************************************
*                      Macros
******************************************************/

/******************************************************
*                    Constants
******************************************************/

/******************************************************
*                   Enumerations
******************************************************/

/******************************************************************************/
/** \addtogroup group_logging_enums
 * Documentation of the enums provided by logging utility.
 *//** \{ */
/******************************************************************************/

/** Logging levels. NOTE: Default value for all facilities is passed in to init call */
typedef enum
{
    CY_PCTRL_LOG_OFF = 0,       /**< Do not print log messages */
    CY_PCTRL_LOG_ERROR,         /**< Print if run-time level is <= CY_PCTRL_LOG_ERROR   */
    CY_PCTRL_LOG_WARNING,       /**< Print if run-time level is <= CY_PCTRL_LOG_WARNING */
    CY_PCTRL_LOG_NOTICE,        /**< Print if run-time level is <= CY_PCTRL_LOG_NOTICE  */
    CY_PCTRL_LOG_INFO,          /**< Print if run-time level is <= CY_PCTRL_LOG_INFO    */
    CY_PCTRL_LOG_DEBUG,         /**< Print if run-time level is <= CY_PCTRL_LOG_DEBUG   */
    CY_PCTRL_LOG_DEBUG1,        /**< Print if run-time level is <= CY_PCTRL_LOG_DEBUG1  */
    CY_PCTRL_LOG_DEBUG2,        /**< Print if run-time level is <= CY_PCTRL_LOG_DEBUG2  */
    CY_PCTRL_LOG_DEBUG3,        /**< Print if run-time level is <= CY_PCTRL_LOG_DEBUG3  */
    CY_PCTRL_LOG_DEBUG4,        /**< Print if run-time level is <= CY_PCTRL_LOG_DEBUG4  */

    CY_PCTRL_LOG_PRINT,         /* Identifies the log messages generated by cy_log_printf calls */

    CY_PCTRL_LOG_MAX
} CY_PCTRL_LOG_LEVEL_T;

/** Log facility type
 * Log facilities allow for separate subsystems to have different run-time log levels for output.
 * This allows for someone working in the Driver subsystem to turn on DEBUG level without turning on
 * DEBUG level for middleware - Makes for less unwanted output during debugging/testing.
 */
typedef enum
{
    CYLF_PCTRL_DEFAULT = 0,     /**< General log message not associated with any specific facility */
    CYLF_PCTRL_MIDDLEWARE,      /**< Middleware facility */

    CYLF_PCTRL_MAX              /**< Must be last, not an actual index */
} CY_PCTRL_LOG_FACILITY_T;

/** \} */

/******************************************************************************/
/** \addtogroup group_pctrl_logging_structures
 * Documentation of the typedefs defined by the logging utility.
 *//** \{ */
/******************************************************************************/

/******************************************************
*                    Structures
******************************************************/

/******************************************************
*                 Type definitions
******************************************************/

/** Prototype for application callback to use the logging message
 */
typedef int (* pctrl_log_output)(CY_PCTRL_LOG_FACILITY_T facility, CY_PCTRL_LOG_LEVEL_T level,
                                 char* logmsg);

/** Prototype for application callback to get current time in milliseconds
 */
typedef cy_rslt_t (* platform_get_time)(uint32_t* time);

/** \} */

/*****************************************************************************/
/**
 *
 *  @addtogroup group_logging_func
 *
 * A logging subsystem provides a set of helper functions to manage logging in the application.
 *
 *  @{
 */
/*****************************************************************************/

/******************************************************
*               Function declarations
******************************************************/
/** Initialize the logging subsystem.
 *
 * @param[in] level           : The initial logging level to use for all facilities
 * @param[in] platform_output : Pointer to the function invoked by the library to output the log
 * messages.
 *                              If this argument is passed as NULL, the library prints the log
 * output
 *                              on the standard output stream (stdio).
 * @param[in] platform_time   : Pointer to the function invoked by the library to get the time.
 *                              If this argument is passed as NULL, the library calls
 *
 * [cy_rtos_get_time](https://cypresssemiconductorco.github.io/abstraction-rtos/html/group__group__abstraction__rtos__time.html)
 *                              function to get the time required for logging.
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_init(CY_PCTRL_LOG_LEVEL_T level, pctrl_log_output platform_output,
                            platform_get_time platform_time);

/** Shutdown the logging subsystem.
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_shutdown(void);

/** Set the platform output routine for log messages.
 *
 * @note If platform_output is NULL, log messages will be discarded.
 *
 * @param[in] platform_output : Pointer to the platform output routine for log messages
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_set_platform_output(pctrl_log_output platform_output);

/** Set the platform routine for getting time stamps for log messages.
 *
 * @note If platform_time is NULL, cy_time_get_time() is used for time stamps.
 *
 * @param[in] platform_time   : Pointer to a platform time routine for log message time stamps
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_set_platform_time(platform_get_time platform_time);

/** Set the logging level for a facility.
 *
 * @param[in] facility  : The facility for which to set the log level
 * @param[in] level     : The new log level to use
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_set_facility_level(CY_PCTRL_LOG_FACILITY_T facility,
                                          CY_PCTRL_LOG_LEVEL_T level);

/** Set the logging level for all facilities.
 *
 * @param[in] level  : The new log level to use
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_set_all_levels(CY_PCTRL_LOG_LEVEL_T level);

/** Get the logging level for a facility.
 *
 * @param[in] facility  : The facility for which to return the log level
 *
 * @return The current log level
 */
CY_PCTRL_LOG_LEVEL_T cy_pctrl_log_get_facility_level(CY_PCTRL_LOG_FACILITY_T facility);

/** Write a log message.
 *
 * @note The format arguments are the same as for printf.
 *
 * @param[in] facility  : The facility for the log message
 * @param[in] level     : Log level of the message
 * @param[in] fmt       : Format control string followed by any optional arguments
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_msg_(CY_PCTRL_LOG_FACILITY_T facility, CY_PCTRL_LOG_LEVEL_T level,
                            const char* fmt, ...);

/** Write a log message bypassing the log level check.
 *
 * @note The format arguments are the same as for printf.
 *
 * @param[in] fmt    : Format control string followed by any optional arguments
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_printf(const char* fmt, ...);

/** Write a log message bypassing the log level check using va_list
 *
 * @note The format arguments are the same as for vprintf.
 *
 * @param[in] fmt   : Format control string
 * @param[in] varg  : va_list of arguments
 *
 * @return cy_rslt_t
 */
cy_rslt_t cy_pctrl_log_vprintf(const char* fmt, va_list varg);

/** @} */


#ifdef __cplusplus
} /* Extern "C" */
#endif

#endif // ifndef CY_PCTRL_LOG_H__

/* --- End of File ------------------------------------------------ */
